[package]
name = "ntag21x"
version = "0.1.0"
edition = "2024"
rust-version = "1.87.0"
categories = ["embedded", "no-std"]
description = "NTAG213/215/216 NFC tag driver"
keywords = ["nfc", "ntag", "no-std", "embedded"]
license = "GPL-3.0-or-later"

[features]
default = []
alloc = ["nfc-forum-tags/alloc"]
std = ["alloc", "nfc-forum-tags/std"]

[dependencies]
heapless = "0.9"
nfc-forum-tags = "0.3"
